SPIRIT-40: disable pushes to branch main or branch preview. Fix logs and updateUserEmail

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -8,4 +8,11 @@ do
 	echo "----YOU CANNOT PUSH TO BRANCH MAIN!----\n"
 	exit 1
 	fi
+
+	if [[ $remote_ref = *"preview"* ]]
+    	then
+    	echo "-------ERROR-------\n"
+    	echo "----YOU CANNOT PUSH TO BRANCH PREVIEW!----\n"
+    	exit 1
+    	fi
 done
