Dev (#1)
Add husky branch restrictions and finish implementing adapter tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,9 @@
 npm run lint
+
+echo "$(git rev-parse --abbrev-ref HEAD)"
+if [[ "$(git rev-parse --abbrev-ref HEAD)" = main ]]
+then
+echo "-------ERROR-------\n"
+echo "----YOU CANNOT COMMIT TO MAIN BRANCH!----\n"
+exit 1
+fi
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,1 +1,11 @@
 npm run test
+
+while read remote_ref
+do
+	if [[ $remote_ref = *"main"* ]]
+	then
+	echo "-------ERROR-------\n"
+	echo "----YOU CANNOT PUSH TO BRANCH MAIN!----\n"
+	exit 1
+	fi
+done
