SPIRIT-40: disable pushes to branch main or branch preview. Fix logs and updateUserEmail

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,3 +6,10 @@ echo "-------ERROR-------\n"
 echo "----YOU CANNOT COMMIT TO MAIN BRANCH!----\n"
 exit 1
 fi
+
+if [[ "$(git rev-parse --abbrev-ref HEAD)" = preview ]]
+then
+echo "-------ERROR-------\n"
+echo "----YOU CANNOT COMMIT TO PREVIEW BRANCH!----\n"
+exit 1
+fi
